/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.online_banking_system_cps406_projecct;

//import newpackage.StartPage;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author kavya
 */
public class MakePayment extends javax.swing.JFrame {

    /**
     * Creates new form MakePayment
     */
    public MakePayment() {
        initComponents();
        jPanel1.setFocusable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Receiver_Name = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        MakePayment_EnterAmt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        AccountSelector = new javax.swing.JComboBox<>();
        Proceed = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        Receiver_Name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Receiver_NameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Receiver_NameFocusLost(evt);
            }
        });
        Receiver_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Receiver_NameActionPerformed(evt);
            }
        });
        Receiver_Name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Receiver_NameKeyPressed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("  Receiver's name :");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("  Make Payment");
        jLabel3.setMaximumSize(new java.awt.Dimension(87, 20));
        jLabel3.setSize(new java.awt.Dimension(52, 12));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Transfer Amount :");

        MakePayment_EnterAmt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                MakePayment_EnterAmtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                MakePayment_EnterAmtFocusLost(evt);
            }
        });
        MakePayment_EnterAmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MakePayment_EnterAmtActionPerformed(evt);
            }
        });
        MakePayment_EnterAmt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                MakePayment_EnterAmtKeyPressed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Select Account :");

        AccountSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Account", "Cheqing Account", "Savings Account", "Credit Account", " " }));
        AccountSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccountSelectorActionPerformed(evt);
            }
        });

        Proceed.setText("Proceed");
        Proceed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProceedMouseClicked(evt);
            }
        });
        Proceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProceedActionPerformed(evt);
            }
        });

        jButton1.setText("LOGOUT");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(414, 414, 414)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Receiver_Name)
                            .addComponent(AccountSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MakePayment_EnterAmt)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(398, 398, 398)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(Cancel)
                        .addGap(375, 375, 375)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(Proceed))))
                .addContainerGap(398, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Receiver_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MakePayment_EnterAmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(AccountSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(Proceed)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(Cancel))
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Receiver_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Receiver_NameActionPerformed

        
    }//GEN-LAST:event_Receiver_NameActionPerformed

    private void AccountSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccountSelectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AccountSelectorActionPerformed

    private void Receiver_NameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Receiver_NameFocusGained
       
        if(Receiver_Name.getText().equals("Enter Reciever's Name")){
            Receiver_Name.setText("");
        }
        
        Receiver_Name.setForeground(Color.BLACK);
        
    }//GEN-LAST:event_Receiver_NameFocusGained

    private void Receiver_NameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Receiver_NameFocusLost
        
        if(Receiver_Name.getText().equals("")){
            Receiver_Name.setText("Enter Reciever's Name");
        }
        
        Receiver_Name.setForeground( Color.BLACK);
    
    }//GEN-LAST:event_Receiver_NameFocusLost

    private void MakePayment_EnterAmtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MakePayment_EnterAmtFocusGained
        
         if(MakePayment_EnterAmt.getText().equals("Enter Amount")){
            MakePayment_EnterAmt.setText("");
        }
        
        MakePayment_EnterAmt.setForeground(Color.BLACK);
    }//GEN-LAST:event_MakePayment_EnterAmtFocusGained

    private void MakePayment_EnterAmtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MakePayment_EnterAmtFocusLost
       
        if(MakePayment_EnterAmt.getText().equals("")){
            MakePayment_EnterAmt.setText("Enter Amount");
        }
        
        MakePayment_EnterAmt.setForeground( Color.BLACK);
    }//GEN-LAST:event_MakePayment_EnterAmtFocusLost

    private void ProceedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProceedMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_ProceedMouseClicked

    private void MakePayment_EnterAmtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MakePayment_EnterAmtKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isLetter(c)){
           MakePayment_EnterAmt.setEditable(false);
        }else {
            MakePayment_EnterAmt.setEditable(true);
        }

    }//GEN-LAST:event_MakePayment_EnterAmtKeyPressed

    private void ProceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProceedActionPerformed
        // TODO add your handling code here:
        
        if ((MakePayment_EnterAmt.getText().equals("")) || (Receiver_Name.getText().equals(" "))){
            JOptionPane.showMessageDialog(null,"Invalid Input");
        }
        else {
                
        JOptionPane.showMessageDialog(null,"Payment Successfull!");
        
        }
    }//GEN-LAST:event_ProceedActionPerformed

    private void Receiver_NameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Receiver_NameKeyPressed
        // TODO add your handling code here:
        char x = evt.getKeyChar();
        if (Character.isLetter(x) || Character.isWhitespace(x) || Character.isISOControl(x)){
           Receiver_Name.setEditable(true);
        }else {
            Receiver_Name.setEditable(false);
        }
    }
//GEN-LAST:event_Receiver_NameKeyPressed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        
        StartPage obj = new StartPage();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void MakePayment_EnterAmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MakePayment_EnterAmtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MakePayment_EnterAmtActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        // TODO add your handling code here:
        dboardnew obj = new dboardnew();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_CancelActionPerformed

          
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MakePayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MakePayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MakePayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MakePayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MakePayment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AccountSelector;
    private javax.swing.JButton Cancel;
    private javax.swing.JTextField MakePayment_EnterAmt;
    private javax.swing.JButton Proceed;
    private javax.swing.JTextField Receiver_Name;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
