/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.online_banking_system_cps406_projecct;
import com.mycompany.online_banking_system_cps406_projecct.Connect;
//import newpackage.StartPage;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

/**
 *
 * @author dhairyapatel
 */
public class signupnow extends javax.swing.JFrame {

    //Declarations
    Boolean connectionSuccess = false;
    static Connection connectionDB = null;
    public String CardNumber;
    /**
     * Creates new form sign up now
     */
    public signupnow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cardExpiryDate = new javax.swing.JLabel();
        signup_CardExpiryDate = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cardNumber = new javax.swing.JLabel();
        signup_CardNumber = new javax.swing.JTextField();
        userName = new javax.swing.JLabel();
        Signup_Username = new javax.swing.JTextField();
        emaildAddress = new javax.swing.JLabel();
        Signup_Email = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        Phone = new javax.swing.JLabel();
        Signup_Phone = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 102, 102));
        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("                 Signup now");

        cardExpiryDate.setText("Card Expiry Date");

        signup_CardExpiryDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signup_CardExpiryDateActionPerformed(evt);
            }
        });

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("mm/yy");

        cardNumber.setText("Card Number");

        signup_CardNumber.setToolTipText("Enter Card Number");
        signup_CardNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signup_CardNumberActionPerformed(evt);
            }
        });

        userName.setText("Username");

        Signup_Username.setToolTipText("Enter Unique Username");
        Signup_Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Signup_UsernameActionPerformed(evt);
            }
        });

        emaildAddress.setText("Email Id: ");

        Signup_Email.setToolTipText("Enter Email Address");
        Signup_Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Signup_EmailActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        Phone.setText("Phone :");

        Signup_Phone.setToolTipText("Enter Phone Number");
        Signup_Phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Signup_PhoneActionPerformed(evt);
            }
        });

        jButton1.setText("NEXT>");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Set Password");

        jLabel3.setText("Confirm Password");

        jPasswordField1.setToolTipText("Enter Password");

        jPasswordField2.setToolTipText("Confirm Password");
        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(Phone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cardExpiryDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(userName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(emaildAddress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(cardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(61, 61, 61)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Signup_Username, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                    .addComponent(Signup_Phone)
                                    .addComponent(Signup_Email)
                                    .addComponent(signup_CardExpiryDate, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                    .addComponent(signup_CardNumber)
                                    .addComponent(jPasswordField1)
                                    .addComponent(jPasswordField2))))
                        .addGap(0, 168, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cardNumber)
                    .addComponent(signup_CardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cardExpiryDate, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signup_CardExpiryDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userName)
                    .addComponent(Signup_Username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emaildAddress)
                    .addComponent(Signup_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Phone)
                    .addComponent(Signup_Phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Signup_UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Signup_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Signup_UsernameActionPerformed

    private void signup_CardExpiryDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signup_CardExpiryDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signup_CardExpiryDateActionPerformed

    private void Signup_EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Signup_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Signup_EmailActionPerformed

    private void Signup_PhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Signup_PhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Signup_PhoneActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        
    }//GEN-LAST:event_jButton2MouseClicked

    private void signup_CardNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signup_CardNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signup_CardNumberActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        /**
         * Takes neccessary details from the user to setup his account and allocates his information required spaces in the database.
         */
        
        System.out.println("Going through button");
        boolean validated = false;
        String userNameString = Signup_Username.getText();
        String emailAddressString =  Signup_Email.getText();
        CardNumber=signup_CardNumber.getText();
        String Userpassword=jPasswordField1.getText();
        String phoneNumber=Signup_Phone.getText();
        String ExpireDate=signup_CardExpiryDate.getText();
        String confirmPassword = jPasswordField2.getText();
        Connection conn = null;
        PreparedStatement stmt = null;
        Statement statement;
        try {
            
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/mysql", "root", "Dhruv123");
            statement = conn.createStatement();
            String sqlCheckPrimaryKey = "SELECT * FROM user_data";
            ResultSet rs = statement.executeQuery(sqlCheckPrimaryKey);
            while(rs.next()){
                String emailDB = rs.getString("email");
                String cardNumberDB = rs.getString("card_number");
                String usernameDB = rs.getString("username");
                
                if(emailDB.equalsIgnoreCase(Signup_Email.getText())){
                     Signup_Username.setForeground(Color.red);       //Using foreground to set to red color
                    Signup_Username.setBorder(BorderFactory.createLineBorder(Color.RED));   //setting boarders to red color
                    Signup_Username.setToolTipText("Email already taken!");
                }
                if(cardNumberDB.equalsIgnoreCase(signup_CardNumber.getText())){
                    Signup_Email.setForeground(Color.red);       //Using foreground to set to red color
                    Signup_Email.setBorder(BorderFactory.createLineBorder(Color.RED));   //setting boarders to red color
                    Signup_Email.setToolTipText("CardNumber already taken!");
                }
                if(usernameDB.equalsIgnoreCase(Signup_Username.getText())){
                    Signup_Username.setForeground(Color.red);       //Using foreground to set to red color
                    Signup_Username.setBorder(BorderFactory.createLineBorder(Color.RED));   //setting boarders to red color
                    Signup_Username.setToolTipText("Username already taken!");
                }
                System.out.println("Data from DB:- \nEmail: "+emailDB+"\ncard number: "+cardNumberDB+"\nusername: "+usernameDB);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(signupnow.class.getName()).log(Level.SEVERE, null, ex);
        } 

        if(validated == false){
        if(Signup_Username.getText().isEmpty()){
            Signup_Username.setForeground(Color.red);       //Using foreground to set to red color
            Signup_Username.setBorder(BorderFactory.createLineBorder(Color.RED));   //setting boarders to red color
            Signup_Username.setToolTipText("Please enter something here!");     //setting the tool tip to show display message when mouse is over the text field
            System.out.println("username is empty");
            validated = false;
        }
        if(Signup_Email.getText().isEmpty()){
            Signup_Email.setForeground(Color.red);
            Signup_Email.setBorder(BorderFactory.createLineBorder(Color.RED));
            Signup_Email.setToolTipText("Please enter something here!"); 
            validated = false;
        }
        if(signup_CardNumber.getText().isEmpty()){
            signup_CardNumber.setForeground(Color.red);
            signup_CardNumber.setBorder(BorderFactory.createLineBorder(Color.RED));
            signup_CardNumber.setToolTipText("Please enter something here!"); 
            validated = false;
        }
        if(jPasswordField1.getText().isEmpty()){
            jPasswordField1.setForeground(Color.red);
            jPasswordField1.setBorder(BorderFactory.createLineBorder(Color.RED));
            jPasswordField1.setToolTipText("Please enter something here!"); 
            validated = false;
        }
        if(Signup_Phone.getText().isEmpty()){
            Signup_Phone.setForeground(Color.red);
            Signup_Phone.setBorder(BorderFactory.createLineBorder(Color.RED));
            Signup_Phone.setToolTipText("Please enter something here!");
            validated = false;
        }
        if(signup_CardExpiryDate.getText().isEmpty()){
            signup_CardExpiryDate.setForeground(Color.red);
            signup_CardExpiryDate.setBorder(BorderFactory.createLineBorder(Color.RED));
            signup_CardExpiryDate.setToolTipText("Please enter something here!"); 
            validated = false;
        }
        if(jPasswordField1.getText() != jPasswordField2.getText()){
            jPasswordField1.setForeground(Color.red);
            jPasswordField1.setBorder(BorderFactory.createLineBorder(Color.RED));
            jPasswordField1.setToolTipText("Passwords does not match!");
            jPasswordField2.setForeground(Color.red);
            jPasswordField2.setBorder(BorderFactory.createLineBorder(Color.RED));
            jPasswordField2.setToolTipText("Passwords does not match!");
            validated = false;
        }
        validated = true;
        }
        
        
    

        if(validated){
        //Stroing to DB
        try{
            // Register JDBC driver
            Class.forName("com.mysql.cj.jdbc.Driver");
            
            // Open a connection
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/mysql", "root", "Dhruv123");

            // Execute SQL query
            String sql = "INSERT INTO user_data (username, email,phone_no, password, card_number, Expire_date) VALUES (?, ?, ?, ?, ?, ?)";
            stmt = conn.prepareStatement(sql);

            // Set parameters
            stmt.setString(1, userNameString);
            stmt.setString(2, emailAddressString);
            stmt.setString(3,CardNumber);
            stmt.setString(4,Userpassword);
            stmt.setString(5,phoneNumber);
            stmt.setString(6,ExpireDate);
            // Execute statement
            int rowsInserted = stmt.executeUpdate();
            if (rowsInserted > 0) {
                System.out.println("Data inserted successfully!");
                StartPage obj = new StartPage();
                obj.setVisible(true);
                dispose();
            }

            } catch (SQLException se) {
                se.printStackTrace();
            } catch (Exception e) {
             e.printStackTrace();
            } finally {
             // Close resources
                try {
                    if (stmt != null)
                    stmt.close();
            } catch (SQLException se2) {
            } // nothing we can do
            try {
                if (conn != null)
                    conn.close();
            } catch (SQLException se) {
                se.printStackTrace();
            }
        }
        }
        
     
    }//GEN-LAST:event_jButton1ActionPerformed
    public String getCardNumber(){
        return CardNumber;
    }
    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
         // Variables declaration - do not modify                     

        //Setting up the connection with sql database
        Connect connect = new Connect();
       
        
        
        
        
        //jButton1.addActionListner(new ActionListener(){
//            @Override
//            public void actionPerformed(ActionEvent e) {
//                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
//            }
//            
//        });
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signupnow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signupnow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signupnow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signupnow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        //Next button click listener
        
     
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signupnow().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Phone;
    private javax.swing.JTextField Signup_Email;
    private javax.swing.JTextField Signup_Phone;
    private javax.swing.JTextField Signup_Username;
    private javax.swing.JLabel cardExpiryDate;
    private javax.swing.JLabel cardNumber;
    private javax.swing.JLabel emaildAddress;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField signup_CardExpiryDate;
    private javax.swing.JTextField signup_CardNumber;
    private javax.swing.JLabel userName;
    // End of variables declaration//GEN-END:variables

    
    

}
